# This is a sample file, for detailed reference see: https://rudderlabs.github.io/pywht/
models:
  - name: user_churn
    model_type: python_model
    model_spec:
      occurred_at_col: insert_ts
      entity_key: user
      validity_time: 24h # 1 day
      py_repo_url: git@github.com:rudderlabs/rudderstack-profiles-classifier.git


      train:
        file_extension: .json
        file_validity: 168h # If the last trained model is older than this, then the model will be trained again,
        inputs:
          # - packages/feature_table/models/user_profile_sample
        config:
          data:
            package_name: feature_table # Name of the package where the profiles feature table is defined (declared in pb_project.yaml packages)
            label_column: is_churned_7_days
            label_value: 1
            prediction_horizon_days: 7
            model_name: 'user_profile_sample'
            entity_column: 'profile_id'
          preprocessing:
            ignore_features: ['campaign_sources', 'campaigns_list', 'mediums_list', 'sources_list']
      predict:
        inputs:
          # - packages/feature_table/models/user_profile_sample
        config:
          data:
            entity_column: 'profile_id'
            model_name: 'user_profile_sample'
          preprocessing:
            ignore_features: ['campaign_sources', 'campaigns_list', 'mediums_list', 'sources_list']
          outputs:
            column_names:
              percentile: &percentile_name percentile_churn_score_7_days
              score: churn_score_7_days
            feature_meta_data: &feature_meta_data
              features:
                - name: *percentile_name
                  description: 'Percentile of churn score. Higher the percentile, higher the probability of churn'
      !!merge <<: *feature_meta_data
