# This is a sample file, for detailed reference see: https://rudderlabs.github.io/pywht/
models:
  - name: shopify_churn
    model_type: python_model
    model_spec:
      occurred_at_col: insert_ts
      entity_key: user
      validity_time: 24h # 1 day
      py_repo_url: https://github.com/rudderlabs/rudderstack-profiles-classifier.git
      predict:
        inputs:
          - packages/feature_table/models/shopify_user_features
        config:
          outputs:
            column_names:
              percentile: &percentile_name percentile_churn_score_7_days
              score: churn_score_7_days
            feature_meta_data: &feature_meta_data
              features:
                - name: *percentile_name
                  description: 'Percentile of churn score. Higher the percentile, higher the probability of churn'
      train:
        file_extension: .json
        file_validity: 60m
        inputs:
          - inputs/feature_table
          - packages/feature_table/models/shopify_user_features
        config:
          data:
            label_column: is_churned_7_days
            label_value: 1
            prediction_horizon_days: 7
            model_name: 'shopify_user_features'
            
      <<: *feature_meta_data