# This is a sample file, for detailed reference see: https://rudderlabs.github.io/pywht/
models:
  - name: &model_name user_churn
    model_type: python_model
    model_spec:
      occurred_at_col: insert_ts
      entity_key: user
      validity_time: 24h # 1 day
      py_repo_url: git@github.com:rudderlabs/rudderstack-profiles-classifier.git


      train:
        file_extension: .json
        file_validity: 168h # If the last trained model is older than this, then the model will be trained again,
        inputs:
          # - packages/feature_table/models/user_profile_sample
        config:
          data: &model_data_input_configs
            label_column: is_churned_7_days
            label_value: 1
            prediction_horizon_days: 7
            features_profiles_model: 'user_profile_sample'
            output_profiles_ml_model: *model_name
            entity_column: 'profile_id'
          preprocessing: &model_data_preprocessing_configs
            ignore_features: ['campaign_sources', 'campaigns_list', 'mediums_list', 'sources_list']
      predict:
        inputs:
          # - packages/feature_table/models/user_profile_sample
        config:
          data: *model_data_input_configs
          preprocessing: *model_data_preprocessing_configs
          outputs:
            column_names:
              percentile: &percentile_name percentile_churn_score_7_days
              score: churn_score_7_days
            feature_meta_data: &feature_meta_data
              features:
                - name: *percentile_name
                  description: 'Percentile of churn score. Higher the percentile, higher the probability of churn'
      !!merge <<: *feature_meta_data
