# This is a sample file, for detailed reference see: https://rudderlabs.github.io/pywht/
models:
  - name: init_ml_project
    model_type: python_model
    model_spec:
      occurred_at_col: insert_ts
      entity_key: user
      validity_time: 24h # 1 day
      # py_repo_url: git@github.com:rudderlabs/ml_repo.git
      py_repo_url: git@github.com:rudderlabs/rudderstack-profiles-classifier.git
      predict:
        inputs:
          - packages/shopify_features/models/shopify_user_features
        config:
          constants:
            material_registry: &material_registry_table material_registry_3
          outputs:
            column_names:
              percentile: &percentile_name percentile_churn_score_7_days
              score: churn_score_7_days
            feature_meta_data: &feature_meta_data
              features:
                - name: *percentile_name
                  description: 'Percentile of churn score. Higher the percentile, higher the probability of churn'
      train:
        file_extension: .json
        file_validity: 60m
        inputs:
          - inputs/feature_table
          - packages/shopify_features/models/shopify_user_features
        config:
          constants:
            material_registry: *material_registry_table
